// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: proto/program.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Program_RepeatMessage_FullMethodName = "/proto.Program/RepeatMessage"
)

// ProgramClient is the client API for Program service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProgramClient interface {
	RepeatMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type programClient struct {
	cc grpc.ClientConnInterface
}

func NewProgramClient(cc grpc.ClientConnInterface) ProgramClient {
	return &programClient{cc}
}

func (c *programClient) RepeatMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, Program_RepeatMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgramServer is the server API for Program service.
// All implementations must embed UnimplementedProgramServer
// for forward compatibility
type ProgramServer interface {
	RepeatMessage(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedProgramServer()
}

// UnimplementedProgramServer must be embedded to have forward compatible implementations.
type UnimplementedProgramServer struct {
}

func (UnimplementedProgramServer) RepeatMessage(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RepeatMessage not implemented")
}
func (UnimplementedProgramServer) mustEmbedUnimplementedProgramServer() {}

// UnsafeProgramServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgramServer will
// result in compilation errors.
type UnsafeProgramServer interface {
	mustEmbedUnimplementedProgramServer()
}

func RegisterProgramServer(s grpc.ServiceRegistrar, srv ProgramServer) {
	s.RegisterService(&Program_ServiceDesc, srv)
}

func _Program_RepeatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramServer).RepeatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Program_RepeatMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramServer).RepeatMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// Program_ServiceDesc is the grpc.ServiceDesc for Program service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Program_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Program",
	HandlerType: (*ProgramServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RepeatMessage",
			Handler:    _Program_RepeatMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/program.proto",
}
